name: Convert data to JSON

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          git clone https://github.com/magnublo/test-decibel-meter-data
          cd test-decibel-meter-data
          
